/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicMarketplaceRouteImport } from './routes/_public/marketplace'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as ProtectedProjectDeveloperLayoutRouteImport } from './routes/_protected/project-developer/_layout'
import { Route as ProtectedCompanyLayoutRouteImport } from './routes/_protected/company/_layout'
import { Route as PublicAuthProjectDeveloperLayoutRouteImport } from './routes/_public/auth/project-developer/_layout'
import { Route as PublicAuthCompanyLayoutRouteImport } from './routes/_public/auth/company/_layout'
import { Route as ProtectedProjectDeveloperLayoutProjectsRouteImport } from './routes/_protected/project-developer/_layout.projects'
import { Route as ProtectedProjectDeveloperLayoutProfileRouteImport } from './routes/_protected/project-developer/_layout.profile'
import { Route as ProtectedProjectDeveloperLayoutOpenmapRouteImport } from './routes/_protected/project-developer/_layout.openmap'
import { Route as ProtectedProjectDeveloperLayoutMarketplaceRouteImport } from './routes/_protected/project-developer/_layout.marketplace'
import { Route as ProtectedProjectDeveloperLayoutDashboardRouteImport } from './routes/_protected/project-developer/_layout.dashboard'
import { Route as ProtectedCompanyLayoutMarketplaceRouteImport } from './routes/_protected/company/_layout.marketplace'
import { Route as ProtectedCompanyLayoutDashboardRouteImport } from './routes/_protected/company/_layout.dashboard'
import { Route as PublicAuthProjectDeveloperLayoutRegisterRouteImport } from './routes/_public/auth/project-developer/_layout.register'
import { Route as PublicAuthProjectDeveloperLayoutLoginRouteImport } from './routes/_public/auth/project-developer/_layout.login'
import { Route as PublicAuthCompanyLayoutRegisterRouteImport } from './routes/_public/auth/company/_layout.register'
import { Route as PublicAuthCompanyLayoutLoginRouteImport } from './routes/_public/auth/company/_layout.login'

const ProtectedProjectDeveloperRouteImport = createFileRoute(
  '/_protected/project-developer',
)()
const ProtectedCompanyRouteImport = createFileRoute('/_protected/company')()
const PublicAuthProjectDeveloperRouteImport = createFileRoute(
  '/_public/auth/project-developer',
)()
const PublicAuthCompanyRouteImport = createFileRoute('/_public/auth/company')()

const ProtectedProjectDeveloperRoute =
  ProtectedProjectDeveloperRouteImport.update({
    id: '/_protected/project-developer',
    path: '/project-developer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedCompanyRoute = ProtectedCompanyRouteImport.update({
  id: '/_protected/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicMarketplaceRoute = PublicMarketplaceRouteImport.update({
  id: '/_public/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/_public/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthProjectDeveloperRoute =
  PublicAuthProjectDeveloperRouteImport.update({
    id: '/_public/auth/project-developer',
    path: '/auth/project-developer',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicAuthCompanyRoute = PublicAuthCompanyRouteImport.update({
  id: '/_public/auth/company',
  path: '/auth/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProjectDeveloperLayoutRoute =
  ProtectedProjectDeveloperLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => ProtectedProjectDeveloperRoute,
  } as any)
const ProtectedCompanyLayoutRoute = ProtectedCompanyLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedCompanyRoute,
} as any)
const PublicAuthProjectDeveloperLayoutRoute =
  PublicAuthProjectDeveloperLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => PublicAuthProjectDeveloperRoute,
  } as any)
const PublicAuthCompanyLayoutRoute = PublicAuthCompanyLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => PublicAuthCompanyRoute,
} as any)
const ProtectedProjectDeveloperLayoutProjectsRoute =
  ProtectedProjectDeveloperLayoutProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ProtectedProjectDeveloperLayoutRoute,
  } as any)
const ProtectedProjectDeveloperLayoutProfileRoute =
  ProtectedProjectDeveloperLayoutProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedProjectDeveloperLayoutRoute,
  } as any)
const ProtectedProjectDeveloperLayoutOpenmapRoute =
  ProtectedProjectDeveloperLayoutOpenmapRouteImport.update({
    id: '/openmap',
    path: '/openmap',
    getParentRoute: () => ProtectedProjectDeveloperLayoutRoute,
  } as any)
const ProtectedProjectDeveloperLayoutMarketplaceRoute =
  ProtectedProjectDeveloperLayoutMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => ProtectedProjectDeveloperLayoutRoute,
  } as any)
const ProtectedProjectDeveloperLayoutDashboardRoute =
  ProtectedProjectDeveloperLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedProjectDeveloperLayoutRoute,
  } as any)
const ProtectedCompanyLayoutMarketplaceRoute =
  ProtectedCompanyLayoutMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => ProtectedCompanyLayoutRoute,
  } as any)
const ProtectedCompanyLayoutDashboardRoute =
  ProtectedCompanyLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedCompanyLayoutRoute,
  } as any)
const PublicAuthProjectDeveloperLayoutRegisterRoute =
  PublicAuthProjectDeveloperLayoutRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => PublicAuthProjectDeveloperLayoutRoute,
  } as any)
const PublicAuthProjectDeveloperLayoutLoginRoute =
  PublicAuthProjectDeveloperLayoutLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => PublicAuthProjectDeveloperLayoutRoute,
  } as any)
const PublicAuthCompanyLayoutRegisterRoute =
  PublicAuthCompanyLayoutRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => PublicAuthCompanyLayoutRoute,
  } as any)
const PublicAuthCompanyLayoutLoginRoute =
  PublicAuthCompanyLayoutLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => PublicAuthCompanyLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/contact': typeof PublicContactRoute
  '/marketplace': typeof PublicMarketplaceRoute
  '/': typeof PublicIndexRoute
  '/company': typeof ProtectedCompanyLayoutRouteWithChildren
  '/project-developer': typeof ProtectedProjectDeveloperLayoutRouteWithChildren
  '/company/dashboard': typeof ProtectedCompanyLayoutDashboardRoute
  '/company/marketplace': typeof ProtectedCompanyLayoutMarketplaceRoute
  '/project-developer/dashboard': typeof ProtectedProjectDeveloperLayoutDashboardRoute
  '/project-developer/marketplace': typeof ProtectedProjectDeveloperLayoutMarketplaceRoute
  '/project-developer/openmap': typeof ProtectedProjectDeveloperLayoutOpenmapRoute
  '/project-developer/profile': typeof ProtectedProjectDeveloperLayoutProfileRoute
  '/project-developer/projects': typeof ProtectedProjectDeveloperLayoutProjectsRoute
  '/auth/company': typeof PublicAuthCompanyLayoutRouteWithChildren
  '/auth/project-developer': typeof PublicAuthProjectDeveloperLayoutRouteWithChildren
  '/auth/company/login': typeof PublicAuthCompanyLayoutLoginRoute
  '/auth/company/register': typeof PublicAuthCompanyLayoutRegisterRoute
  '/auth/project-developer/login': typeof PublicAuthProjectDeveloperLayoutLoginRoute
  '/auth/project-developer/register': typeof PublicAuthProjectDeveloperLayoutRegisterRoute
}
export interface FileRoutesByTo {
  '/contact': typeof PublicContactRoute
  '/marketplace': typeof PublicMarketplaceRoute
  '/': typeof PublicIndexRoute
  '/company': typeof ProtectedCompanyLayoutRouteWithChildren
  '/project-developer': typeof ProtectedProjectDeveloperLayoutRouteWithChildren
  '/company/dashboard': typeof ProtectedCompanyLayoutDashboardRoute
  '/company/marketplace': typeof ProtectedCompanyLayoutMarketplaceRoute
  '/project-developer/dashboard': typeof ProtectedProjectDeveloperLayoutDashboardRoute
  '/project-developer/marketplace': typeof ProtectedProjectDeveloperLayoutMarketplaceRoute
  '/project-developer/openmap': typeof ProtectedProjectDeveloperLayoutOpenmapRoute
  '/project-developer/profile': typeof ProtectedProjectDeveloperLayoutProfileRoute
  '/project-developer/projects': typeof ProtectedProjectDeveloperLayoutProjectsRoute
  '/auth/company': typeof PublicAuthCompanyLayoutRouteWithChildren
  '/auth/project-developer': typeof PublicAuthProjectDeveloperLayoutRouteWithChildren
  '/auth/company/login': typeof PublicAuthCompanyLayoutLoginRoute
  '/auth/company/register': typeof PublicAuthCompanyLayoutRegisterRoute
  '/auth/project-developer/login': typeof PublicAuthProjectDeveloperLayoutLoginRoute
  '/auth/project-developer/register': typeof PublicAuthProjectDeveloperLayoutRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public/contact': typeof PublicContactRoute
  '/_public/marketplace': typeof PublicMarketplaceRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/company': typeof ProtectedCompanyRouteWithChildren
  '/_protected/company/_layout': typeof ProtectedCompanyLayoutRouteWithChildren
  '/_protected/project-developer': typeof ProtectedProjectDeveloperRouteWithChildren
  '/_protected/project-developer/_layout': typeof ProtectedProjectDeveloperLayoutRouteWithChildren
  '/_protected/company/_layout/dashboard': typeof ProtectedCompanyLayoutDashboardRoute
  '/_protected/company/_layout/marketplace': typeof ProtectedCompanyLayoutMarketplaceRoute
  '/_protected/project-developer/_layout/dashboard': typeof ProtectedProjectDeveloperLayoutDashboardRoute
  '/_protected/project-developer/_layout/marketplace': typeof ProtectedProjectDeveloperLayoutMarketplaceRoute
  '/_protected/project-developer/_layout/openmap': typeof ProtectedProjectDeveloperLayoutOpenmapRoute
  '/_protected/project-developer/_layout/profile': typeof ProtectedProjectDeveloperLayoutProfileRoute
  '/_protected/project-developer/_layout/projects': typeof ProtectedProjectDeveloperLayoutProjectsRoute
  '/_public/auth/company': typeof PublicAuthCompanyRouteWithChildren
  '/_public/auth/company/_layout': typeof PublicAuthCompanyLayoutRouteWithChildren
  '/_public/auth/project-developer': typeof PublicAuthProjectDeveloperRouteWithChildren
  '/_public/auth/project-developer/_layout': typeof PublicAuthProjectDeveloperLayoutRouteWithChildren
  '/_public/auth/company/_layout/login': typeof PublicAuthCompanyLayoutLoginRoute
  '/_public/auth/company/_layout/register': typeof PublicAuthCompanyLayoutRegisterRoute
  '/_public/auth/project-developer/_layout/login': typeof PublicAuthProjectDeveloperLayoutLoginRoute
  '/_public/auth/project-developer/_layout/register': typeof PublicAuthProjectDeveloperLayoutRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/contact'
    | '/marketplace'
    | '/'
    | '/company'
    | '/project-developer'
    | '/company/dashboard'
    | '/company/marketplace'
    | '/project-developer/dashboard'
    | '/project-developer/marketplace'
    | '/project-developer/openmap'
    | '/project-developer/profile'
    | '/project-developer/projects'
    | '/auth/company'
    | '/auth/project-developer'
    | '/auth/company/login'
    | '/auth/company/register'
    | '/auth/project-developer/login'
    | '/auth/project-developer/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/marketplace'
    | '/'
    | '/company'
    | '/project-developer'
    | '/company/dashboard'
    | '/company/marketplace'
    | '/project-developer/dashboard'
    | '/project-developer/marketplace'
    | '/project-developer/openmap'
    | '/project-developer/profile'
    | '/project-developer/projects'
    | '/auth/company'
    | '/auth/project-developer'
    | '/auth/company/login'
    | '/auth/company/register'
    | '/auth/project-developer/login'
    | '/auth/project-developer/register'
  id:
    | '__root__'
    | '/_public/contact'
    | '/_public/marketplace'
    | '/_public/'
    | '/_protected/company'
    | '/_protected/company/_layout'
    | '/_protected/project-developer'
    | '/_protected/project-developer/_layout'
    | '/_protected/company/_layout/dashboard'
    | '/_protected/company/_layout/marketplace'
    | '/_protected/project-developer/_layout/dashboard'
    | '/_protected/project-developer/_layout/marketplace'
    | '/_protected/project-developer/_layout/openmap'
    | '/_protected/project-developer/_layout/profile'
    | '/_protected/project-developer/_layout/projects'
    | '/_public/auth/company'
    | '/_public/auth/company/_layout'
    | '/_public/auth/project-developer'
    | '/_public/auth/project-developer/_layout'
    | '/_public/auth/company/_layout/login'
    | '/_public/auth/company/_layout/register'
    | '/_public/auth/project-developer/_layout/login'
    | '/_public/auth/project-developer/_layout/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicMarketplaceRoute: typeof PublicMarketplaceRoute
  PublicIndexRoute: typeof PublicIndexRoute
  ProtectedCompanyRoute: typeof ProtectedCompanyRouteWithChildren
  ProtectedProjectDeveloperRoute: typeof ProtectedProjectDeveloperRouteWithChildren
  PublicAuthCompanyRoute: typeof PublicAuthCompanyRouteWithChildren
  PublicAuthProjectDeveloperRoute: typeof PublicAuthProjectDeveloperRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected/project-developer': {
      id: '/_protected/project-developer'
      path: '/project-developer'
      fullPath: '/project-developer'
      preLoaderRoute: typeof ProtectedProjectDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/company': {
      id: '/_protected/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof ProtectedCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/marketplace': {
      id: '/_public/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof PublicMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/project-developer': {
      id: '/_public/auth/project-developer'
      path: '/auth/project-developer'
      fullPath: '/auth/project-developer'
      preLoaderRoute: typeof PublicAuthProjectDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/company': {
      id: '/_public/auth/company'
      path: '/auth/company'
      fullPath: '/auth/company'
      preLoaderRoute: typeof PublicAuthCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/project-developer/_layout': {
      id: '/_protected/project-developer/_layout'
      path: '/project-developer'
      fullPath: '/project-developer'
      preLoaderRoute: typeof ProtectedProjectDeveloperLayoutRouteImport
      parentRoute: typeof ProtectedProjectDeveloperRoute
    }
    '/_protected/company/_layout': {
      id: '/_protected/company/_layout'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof ProtectedCompanyLayoutRouteImport
      parentRoute: typeof ProtectedCompanyRoute
    }
    '/_public/auth/project-developer/_layout': {
      id: '/_public/auth/project-developer/_layout'
      path: '/auth/project-developer'
      fullPath: '/auth/project-developer'
      preLoaderRoute: typeof PublicAuthProjectDeveloperLayoutRouteImport
      parentRoute: typeof PublicAuthProjectDeveloperRoute
    }
    '/_public/auth/company/_layout': {
      id: '/_public/auth/company/_layout'
      path: '/auth/company'
      fullPath: '/auth/company'
      preLoaderRoute: typeof PublicAuthCompanyLayoutRouteImport
      parentRoute: typeof PublicAuthCompanyRoute
    }
    '/_protected/project-developer/_layout/projects': {
      id: '/_protected/project-developer/_layout/projects'
      path: '/projects'
      fullPath: '/project-developer/projects'
      preLoaderRoute: typeof ProtectedProjectDeveloperLayoutProjectsRouteImport
      parentRoute: typeof ProtectedProjectDeveloperLayoutRoute
    }
    '/_protected/project-developer/_layout/profile': {
      id: '/_protected/project-developer/_layout/profile'
      path: '/profile'
      fullPath: '/project-developer/profile'
      preLoaderRoute: typeof ProtectedProjectDeveloperLayoutProfileRouteImport
      parentRoute: typeof ProtectedProjectDeveloperLayoutRoute
    }
    '/_protected/project-developer/_layout/openmap': {
      id: '/_protected/project-developer/_layout/openmap'
      path: '/openmap'
      fullPath: '/project-developer/openmap'
      preLoaderRoute: typeof ProtectedProjectDeveloperLayoutOpenmapRouteImport
      parentRoute: typeof ProtectedProjectDeveloperLayoutRoute
    }
    '/_protected/project-developer/_layout/marketplace': {
      id: '/_protected/project-developer/_layout/marketplace'
      path: '/marketplace'
      fullPath: '/project-developer/marketplace'
      preLoaderRoute: typeof ProtectedProjectDeveloperLayoutMarketplaceRouteImport
      parentRoute: typeof ProtectedProjectDeveloperLayoutRoute
    }
    '/_protected/project-developer/_layout/dashboard': {
      id: '/_protected/project-developer/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/project-developer/dashboard'
      preLoaderRoute: typeof ProtectedProjectDeveloperLayoutDashboardRouteImport
      parentRoute: typeof ProtectedProjectDeveloperLayoutRoute
    }
    '/_protected/company/_layout/marketplace': {
      id: '/_protected/company/_layout/marketplace'
      path: '/marketplace'
      fullPath: '/company/marketplace'
      preLoaderRoute: typeof ProtectedCompanyLayoutMarketplaceRouteImport
      parentRoute: typeof ProtectedCompanyLayoutRoute
    }
    '/_protected/company/_layout/dashboard': {
      id: '/_protected/company/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof ProtectedCompanyLayoutDashboardRouteImport
      parentRoute: typeof ProtectedCompanyLayoutRoute
    }
    '/_public/auth/project-developer/_layout/register': {
      id: '/_public/auth/project-developer/_layout/register'
      path: '/register'
      fullPath: '/auth/project-developer/register'
      preLoaderRoute: typeof PublicAuthProjectDeveloperLayoutRegisterRouteImport
      parentRoute: typeof PublicAuthProjectDeveloperLayoutRoute
    }
    '/_public/auth/project-developer/_layout/login': {
      id: '/_public/auth/project-developer/_layout/login'
      path: '/login'
      fullPath: '/auth/project-developer/login'
      preLoaderRoute: typeof PublicAuthProjectDeveloperLayoutLoginRouteImport
      parentRoute: typeof PublicAuthProjectDeveloperLayoutRoute
    }
    '/_public/auth/company/_layout/register': {
      id: '/_public/auth/company/_layout/register'
      path: '/register'
      fullPath: '/auth/company/register'
      preLoaderRoute: typeof PublicAuthCompanyLayoutRegisterRouteImport
      parentRoute: typeof PublicAuthCompanyLayoutRoute
    }
    '/_public/auth/company/_layout/login': {
      id: '/_public/auth/company/_layout/login'
      path: '/login'
      fullPath: '/auth/company/login'
      preLoaderRoute: typeof PublicAuthCompanyLayoutLoginRouteImport
      parentRoute: typeof PublicAuthCompanyLayoutRoute
    }
  }
}

interface ProtectedCompanyLayoutRouteChildren {
  ProtectedCompanyLayoutDashboardRoute: typeof ProtectedCompanyLayoutDashboardRoute
  ProtectedCompanyLayoutMarketplaceRoute: typeof ProtectedCompanyLayoutMarketplaceRoute
}

const ProtectedCompanyLayoutRouteChildren: ProtectedCompanyLayoutRouteChildren =
  {
    ProtectedCompanyLayoutDashboardRoute: ProtectedCompanyLayoutDashboardRoute,
    ProtectedCompanyLayoutMarketplaceRoute:
      ProtectedCompanyLayoutMarketplaceRoute,
  }

const ProtectedCompanyLayoutRouteWithChildren =
  ProtectedCompanyLayoutRoute._addFileChildren(
    ProtectedCompanyLayoutRouteChildren,
  )

interface ProtectedCompanyRouteChildren {
  ProtectedCompanyLayoutRoute: typeof ProtectedCompanyLayoutRouteWithChildren
}

const ProtectedCompanyRouteChildren: ProtectedCompanyRouteChildren = {
  ProtectedCompanyLayoutRoute: ProtectedCompanyLayoutRouteWithChildren,
}

const ProtectedCompanyRouteWithChildren =
  ProtectedCompanyRoute._addFileChildren(ProtectedCompanyRouteChildren)

interface ProtectedProjectDeveloperLayoutRouteChildren {
  ProtectedProjectDeveloperLayoutDashboardRoute: typeof ProtectedProjectDeveloperLayoutDashboardRoute
  ProtectedProjectDeveloperLayoutMarketplaceRoute: typeof ProtectedProjectDeveloperLayoutMarketplaceRoute
  ProtectedProjectDeveloperLayoutOpenmapRoute: typeof ProtectedProjectDeveloperLayoutOpenmapRoute
  ProtectedProjectDeveloperLayoutProfileRoute: typeof ProtectedProjectDeveloperLayoutProfileRoute
  ProtectedProjectDeveloperLayoutProjectsRoute: typeof ProtectedProjectDeveloperLayoutProjectsRoute
}

const ProtectedProjectDeveloperLayoutRouteChildren: ProtectedProjectDeveloperLayoutRouteChildren =
  {
    ProtectedProjectDeveloperLayoutDashboardRoute:
      ProtectedProjectDeveloperLayoutDashboardRoute,
    ProtectedProjectDeveloperLayoutMarketplaceRoute:
      ProtectedProjectDeveloperLayoutMarketplaceRoute,
    ProtectedProjectDeveloperLayoutOpenmapRoute:
      ProtectedProjectDeveloperLayoutOpenmapRoute,
    ProtectedProjectDeveloperLayoutProfileRoute:
      ProtectedProjectDeveloperLayoutProfileRoute,
    ProtectedProjectDeveloperLayoutProjectsRoute:
      ProtectedProjectDeveloperLayoutProjectsRoute,
  }

const ProtectedProjectDeveloperLayoutRouteWithChildren =
  ProtectedProjectDeveloperLayoutRoute._addFileChildren(
    ProtectedProjectDeveloperLayoutRouteChildren,
  )

interface ProtectedProjectDeveloperRouteChildren {
  ProtectedProjectDeveloperLayoutRoute: typeof ProtectedProjectDeveloperLayoutRouteWithChildren
}

const ProtectedProjectDeveloperRouteChildren: ProtectedProjectDeveloperRouteChildren =
  {
    ProtectedProjectDeveloperLayoutRoute:
      ProtectedProjectDeveloperLayoutRouteWithChildren,
  }

const ProtectedProjectDeveloperRouteWithChildren =
  ProtectedProjectDeveloperRoute._addFileChildren(
    ProtectedProjectDeveloperRouteChildren,
  )

interface PublicAuthCompanyLayoutRouteChildren {
  PublicAuthCompanyLayoutLoginRoute: typeof PublicAuthCompanyLayoutLoginRoute
  PublicAuthCompanyLayoutRegisterRoute: typeof PublicAuthCompanyLayoutRegisterRoute
}

const PublicAuthCompanyLayoutRouteChildren: PublicAuthCompanyLayoutRouteChildren =
  {
    PublicAuthCompanyLayoutLoginRoute: PublicAuthCompanyLayoutLoginRoute,
    PublicAuthCompanyLayoutRegisterRoute: PublicAuthCompanyLayoutRegisterRoute,
  }

const PublicAuthCompanyLayoutRouteWithChildren =
  PublicAuthCompanyLayoutRoute._addFileChildren(
    PublicAuthCompanyLayoutRouteChildren,
  )

interface PublicAuthCompanyRouteChildren {
  PublicAuthCompanyLayoutRoute: typeof PublicAuthCompanyLayoutRouteWithChildren
}

const PublicAuthCompanyRouteChildren: PublicAuthCompanyRouteChildren = {
  PublicAuthCompanyLayoutRoute: PublicAuthCompanyLayoutRouteWithChildren,
}

const PublicAuthCompanyRouteWithChildren =
  PublicAuthCompanyRoute._addFileChildren(PublicAuthCompanyRouteChildren)

interface PublicAuthProjectDeveloperLayoutRouteChildren {
  PublicAuthProjectDeveloperLayoutLoginRoute: typeof PublicAuthProjectDeveloperLayoutLoginRoute
  PublicAuthProjectDeveloperLayoutRegisterRoute: typeof PublicAuthProjectDeveloperLayoutRegisterRoute
}

const PublicAuthProjectDeveloperLayoutRouteChildren: PublicAuthProjectDeveloperLayoutRouteChildren =
  {
    PublicAuthProjectDeveloperLayoutLoginRoute:
      PublicAuthProjectDeveloperLayoutLoginRoute,
    PublicAuthProjectDeveloperLayoutRegisterRoute:
      PublicAuthProjectDeveloperLayoutRegisterRoute,
  }

const PublicAuthProjectDeveloperLayoutRouteWithChildren =
  PublicAuthProjectDeveloperLayoutRoute._addFileChildren(
    PublicAuthProjectDeveloperLayoutRouteChildren,
  )

interface PublicAuthProjectDeveloperRouteChildren {
  PublicAuthProjectDeveloperLayoutRoute: typeof PublicAuthProjectDeveloperLayoutRouteWithChildren
}

const PublicAuthProjectDeveloperRouteChildren: PublicAuthProjectDeveloperRouteChildren =
  {
    PublicAuthProjectDeveloperLayoutRoute:
      PublicAuthProjectDeveloperLayoutRouteWithChildren,
  }

const PublicAuthProjectDeveloperRouteWithChildren =
  PublicAuthProjectDeveloperRoute._addFileChildren(
    PublicAuthProjectDeveloperRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicMarketplaceRoute: PublicMarketplaceRoute,
  PublicIndexRoute: PublicIndexRoute,
  ProtectedCompanyRoute: ProtectedCompanyRouteWithChildren,
  ProtectedProjectDeveloperRoute: ProtectedProjectDeveloperRouteWithChildren,
  PublicAuthCompanyRoute: PublicAuthCompanyRouteWithChildren,
  PublicAuthProjectDeveloperRoute: PublicAuthProjectDeveloperRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
